[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "SauceCodeProNerdFont" }
bold = { family = "SauceCodeProNerdFont" }
italic = { family = "SauceCodeProNerdFont" }
bold_italic = { family = "SauceCodeProNerdFont" }

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.95

[terminal]
osc52 = "CopyPaste"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
