[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "SauceCodeProNerdFont" }
bold = { family = "SauceCodeProNerdFont" }
italic = { family = "SauceCodeProNerdFont" }
bold_italic = { family = "SauceCodeProNerdFont" }

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.95

[terminal]
osc52 = "CopyPaste"

[[hints.enabled]]
command = "xdg-open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
post_processing = true

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
regex = "(\\.|/|~)[^\\s]*"
post_processing = false
action = "Copy"

[hints.enabled.binding]
key = "I"
mods = "Control|Shift"

[general]
import = ["~/.config/alacritty/github-dark.toml"]
