disabled-modules = []
watch-all = true

[chrome]
[chrome.profile-options]
watch-all-profiles = true
profile = "Default"

[database]
sync-interval = "4s"
path = "/home/alex/.local/share/gosuki/gosuki.db"

[firefox]
[firefox.profile-options]
watch-all-profiles = true
profile = "default"

[github]
github-token = ""
sync-interval = "6h0m0s"

[html-autoimport]
paths = ["/home/alex/.local/share/gosuki/imports"]
