theme = "github_dark_custom"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
text-width = 120
rulers = [120]
popup-border = "all"
default-yank-register = "+"
end-of-line-diagnostics = "disable"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"

[editor.statusline]
left = ["mode", "version-control", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "spinner", "selections", "position-percentage", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape] 
insert = "bar"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-at-text-width = true

[editor.inline-diagnostics] 
cursor-line = "hint"
max-wrap = 25

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
S-g = "goto_last_line"
0 = "goto_line_start"
"$" = "goto_line_end"
"ret" = "goto_word"
V = "select_mode"
"+" = "increment"
"-" = "decrement"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"

[keys.normal.g]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
"^" = "goto_first_nonwhitespace"

[keys.normal.space]
"-" = "hsplit"
"|" = "vsplit"
q = "wclose"

[keys.normal.space.t]
s = ":toggle soft-wrap.enable"
h = ":toggle lsp.display-inlay-hints"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
"C-[" = ["collapse_selection", "normal_mode"]

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-[" = ["collapse_selection", "normal_mode"]
0 = "goto_line_start"
"$" = "goto_line_end"
S-g = "goto_last_line"
